[features]
seeds = false
skip-lint = false
[programs.localnet]
treehoppers_contract = "BgAh9RE8D5119VA1q28MxPMx77mdbYxWc7DPB5ULAB5x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rilwan99/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
